# coding: utf-8

"""
ColiVara

Colivara is a suite of services that allows you to store, search, and retrieve documents based on their visual embeddings.      It is a web-first implementation of the ColPali paper using ColQwen2 as backend model. It works exacly like RAG from the end-user standpoint - but using vision models instead of chunking and text-processing for documents.

The version of the OpenAPI document: 1.0.0
Contact: abdulhaleem@tjmlabs.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from colivara_py.api.collections_api import CollectionsApi


class TestCollectionsApi(unittest.TestCase):
    """CollectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CollectionsApi()

    def tearDown(self) -> None:
        pass

    def test_api_views_create_collection(self) -> None:
        """Test case for api_views_create_collection

        Create Collection
        """
        pass

    def test_api_views_delete_collection(self) -> None:
        """Test case for api_views_delete_collection

        Delete Collection
        """
        pass

    def test_api_views_get_collection(self) -> None:
        """Test case for api_views_get_collection

        Get Collection
        """
        pass

    def test_api_views_list_collections(self) -> None:
        """Test case for api_views_list_collections

        List Collections
        """
        pass

    def test_api_views_partial_update_collection(self) -> None:
        """Test case for api_views_partial_update_collection

        Partial Update Collection
        """
        pass


if __name__ == "__main__":
    unittest.main()
