# coding: utf-8

"""
ColiVara

Colivara is a suite of services that allows you to store, search, and retrieve documents based on their visual embeddings.      It is a web-first implementation of the ColPali paper using ColQwen2 as backend model. It works exacly like RAG from the end-user standpoint - but using vision models instead of chunking and text-processing for documents.

The version of the OpenAPI document: 1.0.0
Contact: abdulhaleem@tjmlabs.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from colivara_py.api.helpers_api import HelpersApi


class TestHelpersApi(unittest.TestCase):
    """HelpersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HelpersApi()

    def tearDown(self) -> None:
        pass

    def test_api_views_file_to_base64(self) -> None:
        """Test case for api_views_file_to_base64

        File To Base64
        """
        pass

    def test_api_views_file_to_imgbase64(self) -> None:
        """Test case for api_views_file_to_imgbase64

        File To Imgbase64
        """
        pass


if __name__ == "__main__":
    unittest.main()
