# Generator Configuration for colivara-py
packageName: colivara_py
projectName: colivara-py
packageUrl: "https://github.com/tjmlabs/colivara-py" 
packageTitle: 'Colivara Python SDK'
infoName: "TJM Labs"
infoEmail: "founders@colivara.com"
infoUrl: "https://colivara.com"
licenceName: "Apache-2.0"
licenseUrl: "https://www.apache.org/licenses/LICENSE-2.0.html"
summary: "Colivara - Visual Document Search and Retrieval SDK"
description: |
  Colivara is a suite of services that allows you to store, search, and retrieve documents
  based on their visual embeddings. It is a web-first implementation of the ColPali paper
  using ColQwen2 as a backend model. It works exactly like RAG from the end-user standpoint -
  but uses vision models instead of chunking and text-processing for documents.
gitHost: github.com
gitUserId: Jonathan-Adly
gitRepoId: colivara-py 
templateDir: ./templates   
pythonVersion: "3.10"

