"""
    ColiVara

    Colivara is a suite of services that allows you to store, search, and retrieve documents based on their visual embeddings.      It is a web-first implementation of the ColPali paper using ColQwen2 as backend model. It works exacly like RAG from the end-user standpoint - but using vision models instead of chunking and text-processing for documents.

    The version of the OpenAPI document: 1.0.0
    Contact: founders@colivara.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

NAME = "colivara-py"
VERSION = "1.5.1"
PYTHON_REQUIRES = ">=3.10" 
LICENSE = "Apache License 2.0"

# Read requirements
with open("requirements.txt") as f:
    REQUIRES = f.read().splitlines()

# Read README
with open("README.md", "r", encoding="utf-8") as f:
    LONG_DESCRIPTION = f.read()

setup(
    name=NAME,
    version=VERSION,
    description="Colivara Python SDK",
    long_description=LONG_DESCRIPTION,
    long_description_content_type='text/markdown',
    author="TJM Labs",
    author_email="founders@colivara.com",
    url="https://github.com/tjmlabs/colivara-py",
    project_urls={
        "Bug Tracker": "https://github.com/tjmlabs/colivara-py/issues",
        "Source Code": "https://github.com/tjmlabs/colivara-py"
    },
    python_requires=PYTHON_REQUIRES,
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    package_data={"colivara_py": ["py.typed"]},
    license=LICENSE,
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Platform :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Typing :: Typed"
    ],
    keywords=[
        "colivara_py",
        "OpenAPI",
        ""
    ],
    zip_safe=False
)
