[metadata]
license_file = LICENSE

[bdist_wheel]
universal = 0

[flake8]
max-line-length = 99
exclude = .git,__pycache__,build,dist,.venv
ignore = E203, W503
per-file-ignores = __init__.py:F401

[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
check_untyped_defs = True

[tool:pytest]
testpaths = test
python_files = test_*.py
addopts = --verbose --cov=colivara_py --cov-report=term-missing