# coding: utf-8

"""
ColiVara

Colivara is a suite of services that allows you to store, search, and retrieve documents based on their visual embeddings.      It is a web-first implementation of the ColPali paper using ColQwen2 as backend model. It works exacly like RAG from the end-user standpoint - but using vision models instead of chunking and text-processing for documents.

The version of the OpenAPI document: 1.0.0
Contact: abdulhaleem@tjmlabs.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from setuptools import setup, find_packages  # type: ignore # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "colivara-py"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.10"
with open("requirements.txt") as f:
    REQUIRES = f.read().splitlines()

with open("README.md", "r", encoding="utf-8") as f:
    LONG_DESCRIPTION = f.read()

setup(
    name=NAME,
    version=VERSION,
    description="ColiVara - Visual Document Search and Retrieval SDK",
    long_description=LONG_DESCRIPTION,
    long_description_content_type="text/markdown",
    author="Abdulhaleem",
    author_email="abdulhaleem@tjmlabs.com",
    url="https://github.com/tjmlabs/colivara-py",
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    python_requires=">=3.8",
    install_requires=REQUIRES,
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords=[
        "colivara",
        "visual search",
        "document retrieval",
        "AI",
        "machine learning",
    ],
    package_data={"colivara_py": ["py.typed"]},
    zip_safe=False,
)
