[tox]
envlist = py310, py311, py312, lint, typecheck

[testenv]
deps=-r{toxinidir}/requirements.txt
     -r{toxinidir}/test-requirements.txt

commands=
   pytest --cov=colivara_py


[testenv:lint]
basepython = python3
skip_install = true
deps = flake8
commands = flake8 colivara_py tests


[testenv:typecheck]
basepython = python3
skip_install = true
deps = mypy
commands = mypy colivara_py