# coding: utf-8

# flake8: noqa
"""
    ColiVara

    Colivara is a suite of services that allows you to store, search, and retrieve documents based on their visual embeddings.      It is a web-first implementation of the ColPali paper using ColQwen2 as backend model. It works exacly like RAG from the end-user standpoint - but using vision models instead of chunking and text-processing for documents.

    The version of the OpenAPI document: 1.0.0
    Contact: founders@colivara.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from colivara_py.models.collection_in import CollectionIn
from colivara_py.models.collection_out import CollectionOut
from colivara_py.models.document_in import DocumentIn
from colivara_py.models.document_in_patch import DocumentInPatch
from colivara_py.models.document_out import DocumentOut
from colivara_py.models.embeddings_in import EmbeddingsIn
from colivara_py.models.embeddings_out import EmbeddingsOut
from colivara_py.models.file_out import FileOut
from colivara_py.models.generic_error import GenericError
from colivara_py.models.generic_message import GenericMessage
from colivara_py.models.key import Key
from colivara_py.models.lookup_enum import LookupEnum
from colivara_py.models.on_enum import OnEnum
from colivara_py.models.page_out import PageOut
from colivara_py.models.page_out_query import PageOutQuery
from colivara_py.models.patch_collection_in import PatchCollectionIn
from colivara_py.models.query_filter import QueryFilter
from colivara_py.models.query_in import QueryIn
from colivara_py.models.query_out import QueryOut
from colivara_py.models.response import Response
from colivara_py.models.search_image_in import SearchImageIn
from colivara_py.models.search_image_out import SearchImageOut
from colivara_py.models.task_enum import TaskEnum
from colivara_py.models.value import Value
from colivara_py.models.webhook_in import WebhookIn
from colivara_py.models.webhook_out import WebhookOut
