# coding: utf-8

"""
    ColiVara

    Colivara is a suite of services that allows you to store, search, and retrieve documents based on their visual embeddings.      It is a web-first implementation of the ColPali paper using ColQwen2 as backend model. It works exacly like RAG from the end-user standpoint - but using vision models instead of chunking and text-processing for documents.

    The version of the OpenAPI document: 1.0.0
    Contact: founders@colivara.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LookupEnum(str, Enum):
    """
    LookupEnum
    """

    """
    allowed enum values
    """
    KEY_LOOKUP = 'key_lookup'
    CONTAINS = 'contains'
    CONTAINED_BY = 'contained_by'
    HAS_KEY = 'has_key'
    HAS_KEYS = 'has_keys'
    HAS_ANY_KEYS = 'has_any_keys'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LookupEnum from a JSON string"""
        return cls(json.loads(json_str))


